/*
 * PORT_private.h
 *
 *  Created on: Sep 28, 2021
 *      Author: dell
 */

#ifndef PORT_PRIVATE_H_
#define PORT_PRIVATE_H_

#define CONCAT(b7,b6,b5,b4,b3,b2,b1,b0)    CONC(b7,b6,b5,b4,b3,b2,b1,b0)
#define CONC(b7,b6,b5,b4,b3,b2,b1,b0)    0b##b7##b6##b5##b4##b3##b2##b1##b0


#define PORTA_DIR  CONCAT(PORTA_PIN7_DIR,PORTA_PIN6_DIR,PORTA_PIN5_DIR,PORTA_PIN4_DIR,PORTA_PIN3_DIR,PORTA_PIN2_DIR,PORTA_PIN1_DIR,PORTA_PIN0_DIR)
#define PORTB_DIR  CONCAT(PORTB_PIN7_DIR,PORTB_PIN6_DIR,PORTB_PIN5_DIR,PORTB_PIN4_DIR,PORTB_PIN3_DIR,PORTB_PIN2_DIR,PORTB_PIN1_DIR,PORTB_PIN0_DIR)
#define PORTC_DIR  CONCAT(PORTC_PIN7_DIR,PORTC_PIN6_DIR,PORTC_PIN5_DIR,PORTC_PIN4_DIR,PORTC_PIN3_DIR,PORTC_PIN2_DIR,PORTC_PIN1_DIR,PORTC_PIN0_DIR)
#define PORTD_DIR  CONCAT(PORTD_PIN7_DIR,PORTD_PIN6_DIR,PORTD_PIN5_DIR,PORTD_PIN4_DIR,PORTD_PIN3_DIR,PORTD_PIN2_DIR,PORTD_PIN1_DIR,PORTD_PIN0_DIR)


#define PORTA_INITIAL_VALUE CONCAT(PORTA_PIN7_INITAIL_VALUE,PORTA_PIN6_INITAIL_VALUE,PORTA_PIN5_INITAIL_VALUE,PORTA_PIN4_INITAIL_VALUE,PORTA_PIN3_INITAIL_VALUE,PORTA_PIN2_INITAIL_VALUE,PORTA_PIN1_INITAIL_VALUE,PORTA_PIN0_INITAIL_VALUE)
#define PORTB_INITIAL_VALUE CONCAT(PORTB_PIN7_INITAIL_VALUE,PORTB_PIN6_INITAIL_VALUE,PORTB_PIN5_INITAIL_VALUE,PORTB_PIN4_INITAIL_VALUE,PORTB_PIN3_INITAIL_VALUE,PORTB_PIN2_INITAIL_VALUE,PORTB_PIN1_INITAIL_VALUE,PORTB_PIN0_INITAIL_VALUE)
#define PORTC_INITIAL_VALUE CONCAT(PORTC_PIN7_INITAIL_VALUE,PORTC_PIN6_INITAIL_VALUE,PORTC_PIN5_INITAIL_VALUE,PORTC_PIN4_INITAIL_VALUE,PORTC_PIN3_INITAIL_VALUE,PORTC_PIN2_INITAIL_VALUE,PORTC_PIN1_INITAIL_VALUE,PORTC_PIN0_INITAIL_VALUE)
#define PORTD_INITIAL_VALUE CONCAT(PORTD_PIN7_INITAIL_VALUE,PORTD_PIN6_INITAIL_VALUE,PORTD_PIN5_INITAIL_VALUE,PORTD_PIN4_INITAIL_VALUE,PORTD_PIN3_INITAIL_VALUE,PORTD_PIN2_INITAIL_VALUE,PORTD_PIN1_INITAIL_VALUE,PORTD_PIN0_INITAIL_VALUE)
#endif /* PORT_PRIVATE_H_ */
